variable "public_key" {
  type = string
  default = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDQy/hKbR0dWWUgSc5+ZgicizsNW/HTKFO4QTZGeie5y1bzVxLgMhl8hk8+1qW18bwRxWjJkoLVaegG0Swnf0Y0luHqo47cl85D2YToInZlEvtu/9sEAte2Lw+eRU1FiHB1g+I3OroidXriP03BXc6PlOC/4OhwnTqOsi8PuWUhKw== Generated By Termius"
}

variable "avail_zone" {
  type = string
  default = "us-east-1a"
}

variable "vpc_ep_svc_name" {
  type = string
  default = "com.amazonaws.us-east-1.s3"
}

variable "config-NetworkMiner" {
  default = "NetworkMiner.desktop"
}

variable "config-45-allow-colord" {
  default = "45-allow-colord.sh"
}
